### ISSUE TITLE
Option to Prevent Prefab From Instantiating as a Child of CompisitionRoot

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#84] opened 2016-01-25 04:26 UTC
I have overridden the creation of the player objects for `NetworkLobbyManager` to use a `GameObjectFactory` before doing what it does. As a result the `NetworkLobbyPlayer` becomes a child of the `CompisitionRoot`. causing the following error to occur.

```
DontDestroyOnLoad only work for root GameObjects or components on root GameObjects.
UnityEngine.Networking.NetworkLobbyPlayer:Start()
```

I also bind the `NetworkLobbyManager` and it too becomes a child of the `CompisitionRoot` making me wonder if that is a problem as well. It doesn't warn in the console due to it calling `DontDestroyOnLoad()` in awake before becoming a child.

**Comment by svermeulen** [comment] 2016-01-26 01:00
I actually think Zenject should be changed to not parent dynamically created objects to the `CompositionRoot` at all.  There isn't really a good reason for this anymore.  I'll make that change.

**Comment by svermeulen** [comment] 2016-01-26 01:06
Ok I've made this change on the `develop` branch.  If you get a chance to try that let me know if that fixes your issue

**Comment by Soren025** [comment] 2016-01-26 13:40
Neat, that should help out.

I can see this causing scene hierarchy clutter for dynamic objects that get created often. You may want to include an example in the readme of a `GameObjectFactory` implementation that sets the parent. Also to add support for `ToTransientPrefab()` to accept a root object name or a preexisting root object to parent into.

**Comment by svermeulen** [comment] 2016-01-31 15:38
One thing that I realized after making this change is that this could cause some potential issues with any gameobjects created by the `GlobalCompositionRoot`.  In that case, it is helpful to always parent new game objects to the `GlobalCompositionRoot` so that they do not get destroyed on scene changes.

This also led me to take another look at how injection on the scene works, and I realized there was a bug there that was causing some objects to be injected on twice, if those objects are loaded from another scene using `DontDestroyOnLoad`.

I've fixed this.  Now, when injection on the scene occurs, it will only inject on objects that are associated with the specific scene (or any decorated scenes) and will not inject on any `DontDestroyOnLoad` objects that have carried over.

There is also a flag on the `SceneCompositionRoot` that allows you to decide whether want to automatically parent new objects to it (note however that for the `GlobalCompositionRoot` there is no flag because this is required).  For the `SceneCompositionRoot` though it can be either and things should work fine.

Also, based on your last suggestion, I added an extra parameter to `BindGameObjectFactory` that allows you to pass a string that will be used to group the objects underneath an empty transform by that name

**Comment by Soren025** [comment] 2016-02-03 23:06
I believe `ToTransientGameObject()` and `ToTransientPrefab()` should also be given methods for parent grouping as well.

**Comment by svermeulen** [comment] 2016-02-03 23:08
This is true

**Comment by Shyrou** [comment] 2016-02-04 16:38
Hi,
I decided to post this here since it is related to the subject discussed, and [the other related issue](https://github.com/modesttree/Zenject/issues/57) is already closed.
In my project I have created several prefabs that represent the screens and widgets in my GUI. I want to instantiate these prefabs as the user navigates, and to do so I have a Factory for each of them. For example:

```
public class LoginScreen : MonoBehaviour {
    [...]
    public class Factory : GameObjectFactory<LoginScreen> { }
}
```

In my installer I have this:

```
public GameObject loginScreenPrefab;
[...]
Container.Bind<ScreenFactory>().ToSingle();
Container.BindGameObjectFactory<LoginScreen.Factory>(loginScreenPrefab);
```

ScreenFactory is a class that centralizes the instantiation of these screens and widgets. I injected the factories for the different prefabs and created a method "CreateScreen (ScreenName name)" that uses the corresponding factory depending on the name received as parameter.

```
public class ScreenFactory {
    [Inject] readonly LoginScreen.Factory loginScreenFactory;
    [...]
    public GameObject CreateScreen(ScreenName name)
    {
        switch (name)
        { 
            case ScreenName.LOGIN:
                return loginScreenFactory.Create().gameObject;
                [...]
        }
    }
}
```

So far so good. The problem arises when I try to set the parent of the instantiated prefab. I have a Canvas already created in my scene and I want it to be the parent of all the dynamically created screens. Something like this:

```
GameObject nextScreen = screenFactory.CreateScreen(viewName);
nextScreen.transform.SetParent(mainCanvas.transform, false);
```

In the hierarchy I see that the prefab is successfully set as child of the Canvas, but I am also getting a NullPointerException. I tried in many ways and have also played around with the newly added flag "Parent to SceneCompositionRoot" and the optional parameter "groupName" in BindGameObjectFactory, but nothing changes (passing a groupName still adds the prefabs to SceneCompositionRoot).
I am pretty new to Zenject and I would really appreciate some help on solving this issue. Thanks in advance.

**Comment by svermeulen** [comment] 2016-02-04 19:50
Where is the NullPointerException occurring?  Is it within Zenject and if so do you have a stacktrace?

**Comment by Shyrou** [comment] 2016-02-08 09:15
The NullPointerException occurs in Unity. This is the stacktrace:

```
NullReferenceException: Object reference not set to an instance of an object
GuiController.GoTo (ScreenName viewName) (at Assets/Scripts/Gui/GuiController.cs:37)
GuiController.Start () (at Assets/Scripts/Gui/GuiController.cs:21)
```

Which corresponds to the call to SetParent on the instantiated prefab:
`nextScreen.transform.SetParent(mainCanvas.transform, false);`

This is the exact same error that would occur when trying to access the transform of a prefab loaded with Resources.Load. In this case we would solve it by calling Instantiate on the loaded prefab:
`Instantiate (Resources.Load ("...")) as GameObject;`

**Comment by svermeulen** [comment] 2016-02-08 22:33
I can't think of what could be causing that.  Code seems fine.  Can you make a minimal example reproducing the issue and post the complete code somewhere?

**Comment by Shyrou** [comment] 2016-02-09 11:01
Now this is odd. I prepared a simple project to reproduce the issue as requested, which is basically a copy paste of my project down to the simplest, and it works. So I think I'm going to start building on top of that and see how it goes.

**Comment by Shyrou** [comment] 2016-02-09 11:40
And now I have it working on the original project as well. Reassigning the prefabs to the installer script is what did the trick. Sometimes I just love Unity... Thanks for your time Steve!

**Closed as completed** 2016-10-22 15:52 UTC
