### ISSUE TITLE
Dependency injection not working on an injected dependency?

### ISSUE THREAD

**Issue by meds** [ssannandeji/Zenject-2019#402] opened 2018-01-26 06:59 UTC
I have the following class:

```
    public class StoryProvider : IStoryProvider
    {

        [Zenject.Inject]
        Zenject.DiContainer m_Container
        {
            get;
            set;
        }
```

Which I install like so:

```
             Container
            .Bind<IStoryProvider>()
            .FromInstance(new StoryProvider())
            .AsSingle();
```

I'm finding that m_Container inside the class is not being set and stays null.

**Comment by svermeulen** [comment] 2018-01-26 17:31
When you use FromInstance, the instance you provide it does not get injected.  This is by design, since sometimes those instances come from outside the container and you don't want to inject it.

You could change it to this:

```
 Container
.Bind<IStoryProvider>()
.To<StoryProvider>()
.AsSingle();
```

Or, if you have to use FromInstance for your problem then you could force injection to occur by doing this:

```
var storyProvider = new StoryProvider();
 Container
.Bind<IStoryProvider>()
.FromInstance(storyProvider)
.AsSingle();

Container.QueueForInject(storyProvider);
```

You could also use `Container.Inject(storyProvider)` however this is bad practice because you should wait until the container is fully 'bound' before resolving/instantiating/injecting

**Closed as completed by svermeulen** 2018-01-26 17:31 UTC
