### ISSUE TITLE
FromNewComponentOnNewPrefab and FromResolveGetter unexpected behaviour

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#462] opened 2018-05-10 03:28 UTC
I'm trying to combo FromNewComponentOnNewPrefab  and FromResolveGetter to do some auto binding but it's not working as I'd expect

```
            [SerializeField] private GameObject _prefab;
            container.BindInterfacesAndSelfTo<Foo>().FromNewComponentOnNewPrefab(_prefab).AsSingle().NonLazy();

            container.Bind<Transform>()
                .FromResolveGetter<Foo>(p => p.transform)
                .AsSingle();

            container.Bind<Rigidbody>()
                .FromResolveGetter<Foo>(p => p.GetComponentInChildren<Rigidbody>())
                .AsSingle();

            ... etc
```

Expected result:
- Prefab instantiated
- Transform and rigidbody bound
- 1 copy of Foo added to instance

Actual Result:
- Prefab instantiated
- Transform and rigidbody bound as expected
- 3 copies of Foo added to instance

Is this a bug or intended behaviour? I'd have thought it should only be a single instance of Foo as it's declared AsSingle()

Alternatively if I do

```
            var instance = container.InstantiatePrefab(_prefab);
            container.BindInterfacesAndSelfTo<Foo>().FromNewComponentOn(instance).AsSingle();
```

It works fine

**Comment by svermeulen** [comment] 2018-05-10 04:54
What version of zenject?  Can't reproduce this behaviour on the version I'm using.  Multiple copies of Foo should not be added

**Comment by tertle** [comment] 2018-05-10 05:25
5.5.1

It's resolving within a subcontainer if that makes a difference.

I'll see if I can get a simple working bugged version for you. 
The above example was stripped back version of what I was doing.

**Comment by svermeulen** [comment] 2018-05-10 05:32
Oh ok I reproduced it now with your version.  This is apparently fixed in develop branch

**Comment by svermeulen** [comment] 2018-05-10 05:35
Can't remember which change fixed this.  I'm going to be making an effort to get the new release out over the next couple weeks.  But if you can't wait until then, you can use the develop branch directly

**Comment by tertle** [comment] 2018-05-10 05:39
Ok thanks. I'll give it a shot.

**Comment by tertle** [comment] 2018-05-10 05:45
Just to confirm. The develop branch fixed the issue.

**Closed as completed** 2018-06-04 10:03 UTC
