### ISSUE TITLE
Circular dependency error for field injection?

### ISSUE THREAD

**Issue by darshanshankar** [ssannandeji/Zenject-2019#282] opened 2017-06-18 05:47 UTC
I'm upgrading a project that was previously working fine, Zenject 4.4. We're now on Unity 5.6.1 and I decided to try upgrading to the latest Zenject 5.2.0.

However, I'm getting a circular dependency error that previously wasn't occurring.

`ZenjectException: Found circular dependency when creating type 'Assets.Scripts.Hands.DesktopPointer'. Object graph: LocalHandActivity`

I'm only using field injection, see example:

```
namespace Assets.Scripts.Hands
{
    [RequireComponent(typeof(DesktopInputController))]
    public class DesktopPointer : MonoBehaviour
    {
        ...
        [Inject(Id = "LeftHand")] LocalHandActivity LeftHand;
        [Inject(Id = "RightHand")] LocalHandActivity RightHand;
        [Inject] DesktopInputController desktopInput;
        ...
```

All three of those have references to `DesktopPointer` as well, similarly using field injection.

Why is this error occurring now?

**Comment by svermeulen** [comment] 2017-06-18 13:47
Field injection should work fine with circular dependencies.  This error about circular dependencies should only ever occur when you're using contructor parameters.

So this could potentially be a bug.  Any chance you can reduce your example down to something we can reproduce on our end?  This could involve a more complex chain of dependencies than just the two classes you're using here.  What are the constructor parameters for each of these classes?

**Comment by Soren025** [comment] 2017-06-18 14:53
If what he is doing is what I am showing below then I too am interested in this issue if it is in fact a bug.

```csharp
public class Manager
{
    [Inject]
    private Foo foo;
    [Inject]
    private Bar bar;
    [Inject]
    private Bass bass;
}

public class Foo
{
    [Inject]
    private Manager manager;
}

public class Bar
{
    [Inject]
    private Manager manager;
}

public class Bass
{
    [Inject]
    private Manager manager;
}

public class Installer : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.Bind<Manager>().AsSingle();
        Container.Bind<Foo>().AsSingle();
        Container.Bind<Bar>().AsSingle();
        Container.Bind<Bass>().AsSingle();
    }
}
```

For me this will throw the warning above, I always chalked it up to intentional behaviour because circular dependencies are a tricky thing to deal with

@darshanshankar My work around is the following means of installing the objects. Note in my case all objects involved are singles, so if that is not the case for you some adjustment may be required. Not to difficult tho, it is just a matter of creating the `Manager` object yourself and adding the `WithArguments(manager)` to any binding that is injected into the `Manager`, but also want to have the `Manager` injected into it.

```csharp
public class Installer : MonoInstaller
{
    public override void InstallBindings()
    {
        Manager manager = new GameObject("Manager").AddComponent<Manager>();

        Container.BindInstance(manager).AsSingle();
        Container.QueueForInject(manager)

        Container.Bind<Foo>().AsSingle().WithArguments(manager);
        Container.Bind<Bar>().AsSingle().WithArguments(manager);
        Container.Bind<Bass>().AsSingle().WithArguments(manager);
    }
}
```

**Comment by svermeulen** [comment] 2017-06-18 15:09
@Soren025 What version of zenject?  I just tried your example code and didn't encounter the error

**Comment by Soren025** [comment] 2017-06-18 15:18
@svermeulen Wow, when you replied that my example worked I was surprised.

I encountered that issue in an earlier version and have since updated Zenject after working around it. But I refactored my installer to install normally and it still works unlike before.

**Edit:** I to am currently on Zenject 5.2.0

**Edit 2:** I am now curious how you have things setup now @darshanshankar

**Comment by darshanshankar** [comment] 2017-06-18 20:18
All these classes (`DesktopPointer, DesktopInputController, LocalHandActivity`) are MonoBehaviours

First in a master scene installer:
`
Container.BindInstance(_settings.Monitors.desktopPointers).AsSingle();
Container.BindInstance(_settings.Monitors.desktopInput).AsSingle();
`

I also have a VRInstaller which installs LocalHandActivity based on the VR SDK detected.
`
Container.Bind<LocalHandActivity>().WithId("LeftHand").FromInstance(_vrSettings.OVR.LeftHand);
Container.Bind<LocalHandActivity>().WithId("RightHand").FromInstance(_vrSettings.OVR.RightHand);
`

**Comment by darshanshankar** [comment] 2017-06-20 23:22
Just following up here. I'm still getting this error on many versions of Zenject since 4.4, not just the 5.x versions. Am I installing incorrectly? Why isn't this a circular dep error on 4.4, but an error in future versions?

**Comment by svermeulen** [comment] 2017-06-24 00:39
I had some time tonight so tried to take a look at this again based on your description but found it works as expected.  Can you provide a MRE (minimal reproducible example) that I can use to reproduce?  If so I'd be happy to dig further

**Comment by altunsercan** [comment] 2017-08-07 07:33
Hello everyone, I may be necroing an old issue but since it is still open I thought it was ok.

I have a similar problem with circular injection, but through trial and error managed to make a replicable test case. 
```C#
public class Installer : MonoInstaller<Installer>
{
    public override void InstallBindings()
    {
        Container.Bind<FireStarter>().To<FireStarter>().AsSingle();  
        Container.Bind<Foo>().To<Foo>().AsSingle();
        var bar = this.gameObject.GetComponent<Bar>();
            
        Container.Bind<Bar>().FromInstance(bar).AsSingle();

        Container.Bind<IInitializable>().To<Initializer>().AsSingle();
    }
}
    public class FireStarter
    {
        [Inject] public Bar bar;
    }
    
    public class Bar : MonoBehaviour 
    {
        [Inject] public Foo foo;
    }
    public class Foo
    {
        [Inject] public Bar bar;
    }

    public class Initializer : IInitializable
    {
        [Inject] public FireStarter starter;
        
        public void Initialize()
        {
            
        }
    }

```

So here are my findings:
- Circular dependency error does not occur with only two classes Foo and Bar. Bar->Foo->Bar
- It only happens when injection sequence is FireStarter->Bar->Foo->Bar
- It is also important that Bar is a MonoBehaviour that is already on scene, added as an Instance Binding.
- I tried it with MonoBehaviour recently added with gameObject.AddComponent<Bar>(). It didn't create a problem. Only occured with gameObject.GetComponent<Bar>();

I debugged the code to see that `_isCreatingInstance`  flag remains true in `CachedProvider` after Firestarter->Bar  injection, and this causes error when injection steps into Foo->Bar. I have looked into `InstanceProvider` since it seems to be part of the issue but my debugger could not inspect variables inside a coroutine so I couldn't check for problem values.

I hope this helps you find the issue.

**Comment by svermeulen** [comment] 2017-08-12 14:49
Thanks!  This did help me narrow down the issue.  This should hopefully be fixed now.  Please let me know if it pops up again

**Closed as completed by svermeulen** 2017-08-12 14:49 UTC
