### ISSUE TITLE
Issue with Factory template parameter of type "Type"

### ISSUE THREAD

**Issue by Alphadamos** [ssannandeji/Zenject-2019#132] opened 2016-08-05 02:41 UTC
I made an empty project that started similar to the [Custom Factory Example](https://github.com/modesttree/Zenject/blob/master/Documentation/Factories.md#custom-factories), with the addition of passing a "Type" parameter into the Create() methods. My intent was to use the Type to discern which derived class was to be instantiated in the Create() method.

However, using Type as a parameter will throw an exception, originating from an Assert in the FactoryProvider (line 90) comparing the "typeof(Type)" (System.Type) to "GetType()" of Type (System.MonoType).

To get around this, I changed the InjectUtil.CreateTypePair() method.
previous:
`return new TypeValuePair(param == null ? typeof(T) : param.GetType(), param);`
current:
`Type type = typeof(T);`
`if (param != null && type != typeof(Type))`
`{`
`type = param.GetType();`
`}`
`return new TypeValuePair(type, param);`

Is this a desirable fix or will this cause other issues?

**Comment by svermeulen** [comment] 2016-08-06 15:46
Yeah I see what you mean.  I can reproduce this error.

I think it is (probably) less error prone if InjectUtil.CreateTypePair attempts to always use the most derived type when it is available, since derived types should always work when applied to constructors that take one of their base types but not the other way around.

So I think the actual bug is with the assert itself.  I've just pushed a fix to the assert to make sure it the given type derives from or is equal to the expected type - c2a0b8fc551367c93f0588e7667b776d7a59eb93

Thanks

**Closed as completed by svermeulen** 2016-08-06 15:46 UTC
