### ISSUE TITLE
Injecting dynamically loaded object

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#231] opened 2017-03-09 04:50 UTC
I have a Settings object (MonoBehaviour) that is being loaded from a bundle, but the problem is that many other objects depend on that Settings object.

How can I make sure that the other objects are created automatically when all of the required dependencies (including the Settings object) are resolved? Using NonLazy() makes it throw an exception because obviously the Settings object doesn't exist. Using Lazy() will never instantiate that object because it is not called from anywhere.

I could implement an event handler on the Settings object that would create the other objects that depend on it once it is created, but is there a better option using Zenject? Something like:

```
Container.Bind<PeopleManager>().AsSingle().NonLazyWhenDependencyIsResolved<Settings>();

public class PeopleManager{
   [Inject]
   private PeopleManager( Settings settings ){}    // Gets called as soon as Settings object is loaded.
}
```

**Comment by suzdalnitski** [comment] 2017-03-29 11:52
The solution I arrived at is subscribing to an `OnLoaded `event of a desired object:

```c#
public class Settings {
	private Settings() {
		InitLoadedCallback();
	}

	public static event Action<Settings> OnLoaded;

	private void InitLoadedCallback()
	{
		Action callLoadedCallbackOnce = () => {
					if (OnLoaded != null && this != null) {
						OnLoaded(this);
						OnLoaded = null;
					}
				};

		GlobalObject.OnUpdate += callLoadedCallbackOnce;
	}
}
```

Then in a consumer class:
```c#
public class SettingsConsumer {
	public SettingsConsumer() {
		Settings.OnLoaded += InitWithSettings;
	}

	private void InitWithSettings(Settings settings) {
		// Do stuff with Settings
	}
}
```

**Comment by svermeulen** [comment] 2017-04-02 00:43
This sounds like a duplicate of #243 (please correct me if I'm wrong)

**Closed as completed by svermeulen** 2017-04-02 00:43 UTC
