### ISSUE TITLE
Add support to instantiate and inject ScriptableObjects

### ISSUE THREAD

**Issue by code-beans** [ssannandeji/Zenject-2019#127] opened 2016-06-21 22:01 UTC
It would be nice to have utility functions in the DIContainter to not only instantate and auto-inject Prefabs of type `GameObject` but also `ScriptableObjects`

So similar to `public GameObject InstantiatePrefab(GameObject prefab, params object[] args)`

we'd have 
`public GameObject InstantiateScriptableObject(ScriptableObject prefab, params object[] args)`

**Comment by svermeulen** [comment] 2016-06-21 22:16
You can instantiate new scriptable objects by calling `Container.Instantiate<MyScriptableObject>()`.  (This will automatically call ScriptableObject.CreateInstance)  But you can't instantiate them from resources so a method for that should be added

**Comment by janus007** [comment] 2016-08-30 21:33
Is it possible to configure the settings in code as default, instead of using the editor?

Update:
I can answer this by myself, it was simple to solve. Just recreate the Installers from the the context menu of the settings file.

**Comment by svermeulen** [comment] 2016-09-01 17:53
I'm not sure I follow.  Can you elaborate on what you mean by configuring settings in code?

**Comment by janus007** [comment] 2016-09-01 18:03
Yes.. for instance. If I would raise a signal from the settings editor, i.e. following your advice with settings files and scriptable objects. Let us say a bool true/ false, I've converted that property to a ReactiveExtension property so an event can be raised upon check on/off. At least I can write it the the debug.log without having the scene running.
The signal could be raised via Zenject.Signal. 
The problem is that I can't inject a signal/ instance into the settings class. It is obvious that the Signal only will work with the rest of the classes when the scene is running.
As I understand it, the settings scriptable object is instantiated correct, but without the possibility to inject anything.

**Comment by svermeulen** [comment] 2016-09-01 21:16
Oh you're talking about using Zenject with Editor scripts like custom property editors.  There isn't a lot of examples of doing that kind of thing.  I've played around with some ideas there though.  The issue there is, where does the DiContainer get stored?

There is support for creating EditorWindow derived classes that use Zenject.  You can play with this by just right clicking underneath an Editor directory in the Project tab and then selecting Create -> Zenject -> EditorWindow.  This works nicely because it means you can also add ITickable / IInitializable / IDisposable classes since there are EditorWindow events that correspond to those interfaces

**Comment by thetmkay** [comment] 2017-01-31 20:46
@svermeulen - on this topic: I'm new to Zenject (and IOC) but what's the suggested workaround for injecting pre-instantiated ScriptableObjects?

We have a set of ScriptableObjects saved as assets in the project that we want to load on Init through Zenject and in order to inject dependencies it seems we have to manually call 'Container.Inject(scriptableObjectInstance)'. However the only place to do that seems to be in an Installer - but what about dependencies that are yet to be bound (i.e. on an installer that will be called after this installer). From my understanding it's bad practice to enforce/assume an ordering of installers (let alone I'm not sure how to order ScriptableObjectInstallers vs MonoInstallers), so how/when do we call the manual inject method - or is there another way to inject the object (without using CreateInstance, which will mean we lose our in-editor settings).

**Comment by svermeulen** [comment] 2017-02-02 21:15
Yeah I know what you mean.  Best way to handle this is to use `Container.LazyInstanceInjector`.  You can call `Container.LazyInstanceInjector.AddInstances` and add all the instances of your scriptable objects there.  Then, all your SO's will be injected at the same time zenject does the initial resolve.

The LazyInstanceInjector is also nice because it will inject in the right order.  This way, you can assume that all the objects injected into a given class have themselves been injected.

**Comment by thetmkay** [comment] 2017-02-02 23:17
Cool, thanks 👍

**Comment by svermeulen** [comment] 2017-02-10 02:44
Added support for binding to scriptable object resource paths and also DiContainer.InstantiateScriptableObjectResource method in version 5

**Closed as completed by svermeulen** 2017-02-10 02:44 UTC
